steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/tienda-repo/tienda-web:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/tienda-repo/tienda-web:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment/tienda-web
  - php=us-central1-docker.pkg.dev/$PROJECT_ID/tienda-repo/tienda-web:$SHORT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=mi-cluster-pro'

options:
  logging: CLOUD_LOGGING_ONLY
